// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: IndustrialOven

#include "ui.h"
#include <stdio.h>
#include <stdlib.h>
#include "global_vars.h"
#include <stdbool.h>

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_mainDashboardAuto = NULL;
lv_obj_t * ui_preset1 = NULL;
lv_obj_t * ui_preset2 = NULL;
lv_obj_t * ui_preset3 = NULL;
lv_obj_t * ui_startOpAuto = NULL;
lv_obj_t * ui_doorStatusAuto = NULL;
lv_obj_t * ui_ovenStatusAuto = NULL;

// event functions
void ui_event_mainDashboardAuto(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_preset1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        // Set selected global variables
        selected_dryTime = 9;
        selected_temperature = 60;
    }
}

void ui_event_preset2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        // Set selected global variables
        selected_dryTime = 6;
        selected_temperature = 80;
    }
}

void ui_event_preset3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        // Set selected global variables
        selected_dryTime = 3;
        selected_temperature = 105;
    }
}

void ui_event_startOpAuto(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        // Check if a preset was selected before starting
        if (selected_dryTime > 0) {
            ui_Screen2_start_countdown = true; // Flag to potentially start timer on next Screen2 init
            _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Screen2_screen_init);
        }
    }
}

// build functions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);

    ui_Image1 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image1, &ui_img_1694766395);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);  /// 272
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);

    ui_mainDashboardAuto = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_mainDashboardAuto, 109);
    lv_obj_set_height(ui_mainDashboardAuto, 27);
    lv_obj_set_x(ui_mainDashboardAuto, -40);
    lv_obj_set_y(ui_mainDashboardAuto, -108);
    lv_obj_set_align(ui_mainDashboardAuto, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mainDashboardAuto, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_mainDashboardAuto, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_opa(ui_mainDashboardAuto, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_mainDashboardAuto, ui_event_mainDashboardAuto, LV_EVENT_ALL, NULL);

    ui_preset1 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_preset1, 109);
    lv_obj_set_height(ui_preset1, 27);
    lv_obj_set_x(ui_preset1, -10);
    lv_obj_set_y(ui_preset1, -25);
    lv_obj_set_align(ui_preset1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_preset1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_preset1, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_opa(ui_preset1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_preset1, ui_event_preset1, LV_EVENT_ALL, NULL);

    ui_preset2 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_preset2, 109);
    lv_obj_set_height(ui_preset2, 27);
    lv_obj_set_x(ui_preset2, -10);
    lv_obj_set_y(ui_preset2, 13);
    lv_obj_set_align(ui_preset2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_preset2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_preset2, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_opa(ui_preset2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_preset2, ui_event_preset2, LV_EVENT_ALL, NULL);

    ui_preset3 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_preset3, 109);
    lv_obj_set_height(ui_preset3, 27);
    lv_obj_set_x(ui_preset3, -9);
    lv_obj_set_y(ui_preset3, 49);
    lv_obj_set_align(ui_preset3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_preset3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_preset3, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_opa(ui_preset3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_preset3, ui_event_preset3, LV_EVENT_ALL, NULL);

    ui_startOpAuto = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_startOpAuto, 109);
    lv_obj_set_height(ui_startOpAuto, 27);
    lv_obj_set_x(ui_startOpAuto, 60);
    lv_obj_set_y(ui_startOpAuto, 113);
    lv_obj_set_align(ui_startOpAuto, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_startOpAuto, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_startOpAuto, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_opa(ui_startOpAuto, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_startOpAuto, ui_event_startOpAuto, LV_EVENT_ALL, NULL);

    ui_doorStatusAuto = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_doorStatusAuto, 79);
    lv_obj_set_height(ui_doorStatusAuto, 19);
    lv_obj_set_x(ui_doorStatusAuto, -168);
    lv_obj_set_y(ui_doorStatusAuto, 56);
    lv_obj_set_align(ui_doorStatusAuto, LV_ALIGN_CENTER);
    lv_label_set_text(ui_doorStatusAuto, "Unlocked");

    ui_ovenStatusAuto = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_ovenStatusAuto, 79);
    lv_obj_set_height(ui_ovenStatusAuto, 19);
    lv_obj_set_x(ui_ovenStatusAuto, -168);
    lv_obj_set_y(ui_ovenStatusAuto, 80);
    lv_obj_set_align(ui_ovenStatusAuto, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ovenStatusAuto, "Safe");
}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    ui_Screen3 = NULL;
    ui_Image1 = NULL;
    ui_mainDashboardAuto = NULL;
    ui_preset1 = NULL;
    ui_preset2 = NULL;
    ui_preset3 = NULL;
    ui_startOpAuto = NULL;
    ui_doorStatusAuto = NULL;
    ui_ovenStatusAuto = NULL;
}
