// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: IndustrialOven

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Image1;
extern void ui_event_mainDashboardAuto(lv_event_t * e);
extern lv_obj_t * ui_mainDashboardAuto;
extern lv_obj_t * ui_preset1;
extern lv_obj_t * ui_preset2;
extern lv_obj_t * ui_preset3;
extern lv_obj_t * ui_startOpAuto;
extern lv_obj_t * ui_doorStatusAuto;
extern lv_obj_t * ui_ovenStatusAuto;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

