// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: IndustrialOven

#include "ui.h"
#include <stdio.h>
#include <stdlib.h>
#include "global_vars.h"
#include <stdbool.h>

extern int selected_dryTime;
extern int selected_temperature;
extern bool ui_Screen2_start_countdown;
extern int potenTempValue;
extern int potenTimeValue;
extern bool ui_Screen2_update_manual;

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_HomeButton = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Notif = NULL;
lv_obj_t * ui_NotifLabel = NULL;
lv_obj_t * ui_SimTemp = NULL;
lv_obj_t * ui_dryTime = NULL;
lv_obj_t * ui_temperature = NULL;
lv_obj_t * ui_autoOp1 = NULL;
lv_obj_t * ui_autoLabel = NULL;
lv_obj_t * ui_manOp = NULL;
lv_obj_t * ui_manLabel = NULL;
lv_obj_t * ui_doorStatus = NULL;
lv_obj_t * ui_ovenStatus = NULL;
lv_obj_t * ui_greenCircle = NULL;
lv_obj_t * ui_redCircle = NULL;
lv_obj_t * ui_Keyboard1 = NULL;

// event functions
void ui_event_HomeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_SimTemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard1, ui_SimTemp);
        lv_obj_clear_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN); // Show keyboard
    }

    if(event_code == LV_EVENT_READY) {
        const char * temp_str = lv_textarea_get_text(ui_SimTemp);
        int temp = 0;
        if (temp_str && strlen(temp_str) > 0) temp = atoi(temp_str);

        // --- Update doorStatus ---
        if (temp >= 50)
            lv_label_set_text(ui_doorStatus, "Locked");
        else
            lv_label_set_text(ui_doorStatus, "Unlocked");

        // --- Update ovenStatus + circles ---
        if (temp >= 200) {
            lv_label_set_text(ui_ovenStatus, "Unsafe");
            lv_obj_add_flag(ui_greenCircle, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_redCircle, LV_OBJ_FLAG_HIDDEN);
        } else {
            lv_label_set_text(ui_ovenStatus, "Safe");
            lv_obj_clear_flag(ui_greenCircle, LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(ui_redCircle, LV_OBJ_FLAG_HIDDEN);
        }

        // --- Update notification label ---
        if (temp < 50)
            lv_label_set_text(ui_NotifLabel, "Oven is cold. Safe to handle.");
        else if (temp < 150)
            lv_label_set_text(ui_NotifLabel, "Oven warming up. Caution advised.");
        else if (temp < 200)
            lv_label_set_text(ui_NotifLabel, "Oven hot. Avoid direct contact.");
        else
            lv_label_set_text(ui_NotifLabel, "Warning: High temperature! Dangerous to operate.");

        // After you update labels:
        const char *temp_str1 = lv_textarea_get_text(ui_SimTemp);
        const char *status_str = lv_label_get_text(ui_doorStatus);
        const char *oven_str = lv_label_get_text(ui_ovenStatus);

        // force disable if ANY are empty!
        if (temp_str1 == NULL || strlen(temp_str1) == 0 ||
            status_str == NULL || strlen(status_str) == 0 ||
            oven_str == NULL || strlen(oven_str) == 0) {
            lv_obj_add_state(ui_manOp, LV_STATE_DISABLED);
            lv_obj_add_state(ui_autoOp1, LV_STATE_DISABLED);
        } else {
            // Normal enable/disable by temperature (your logic)
            if (atoi(temp_str1) < 50) {
                lv_obj_clear_state(ui_manOp, LV_STATE_DISABLED);
                lv_obj_clear_state(ui_autoOp1, LV_STATE_DISABLED);
            } else {
                lv_obj_add_state(ui_manOp, LV_STATE_DISABLED);
                lv_obj_add_state(ui_autoOp1, LV_STATE_DISABLED);
            }
        }
    }
}

void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY || event_code == LV_EVENT_CANCEL) {
        lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);       // hide keyboard on OK or Cancel
    }
}

void ui_event_autoOp1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_manOp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_redCircle(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_opacity_set(ui_redCircle, 255);
        _ui_opacity_set(ui_greenCircle, 0);
    }
}

// build functions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_row(ui_Screen2, 20, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Screen2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Image12 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image12, &ui_img_1694772545);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 272
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeButton = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_HomeButton, 100);
    lv_obj_set_height(ui_HomeButton, 20);
    lv_obj_set_x(ui_HomeButton, 1);
    lv_obj_set_y(ui_HomeButton, -120);
    lv_obj_set_align(ui_HomeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 0
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 2);
    lv_obj_set_y(ui_Label3, -120);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Home");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Notif = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Notif, 181);
    lv_obj_set_height(ui_Notif, 72);
    lv_obj_set_x(ui_Notif, 5);
    lv_obj_set_y(ui_Notif, -41);
    lv_obj_set_align(ui_Notif, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Notif, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Notif, lv_color_hex(0x083E38), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Notif, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NotifLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_NotifLabel, 167);
    lv_obj_set_height(ui_NotifLabel, 60);
    lv_obj_set_x(ui_NotifLabel, 6);
    lv_obj_set_y(ui_NotifLabel, -42);
    lv_obj_set_align(ui_NotifLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NotifLabel, "");

    ui_SimTemp = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_SimTemp, 105);
    lv_obj_set_height(ui_SimTemp, 33);
    lv_obj_set_x(ui_SimTemp, 150);
    lv_obj_set_y(ui_SimTemp, 97);
    lv_obj_set_align(ui_SimTemp, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_SimTemp, 3);
    lv_obj_set_style_pad_row(ui_SimTemp, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SimTemp, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dryTime = lv_label_create(ui_Screen2);
        lv_obj_set_width(ui_dryTime, LV_SIZE_CONTENT);   /// 1
        lv_obj_set_height(ui_dryTime, LV_SIZE_CONTENT);    /// 1
        lv_obj_set_x(ui_dryTime, 172); // Set X coordinate
        lv_obj_set_y(ui_dryTime, -56); // Set Y coordinate
        lv_obj_set_align(ui_dryTime, LV_ALIGN_CENTER);
        lv_label_set_text(ui_dryTime, "0"); // Default

        ui_temperature = lv_label_create(ui_Screen2);
        lv_obj_set_width(ui_temperature, LV_SIZE_CONTENT);   /// 1
        lv_obj_set_height(ui_temperature, LV_SIZE_CONTENT);    /// 1
        lv_obj_set_x(ui_temperature, 172); // Set X coordinate
        lv_obj_set_y(ui_temperature, -24); // Set Y coordinate
        lv_obj_set_align(ui_temperature, LV_ALIGN_CENTER);
        lv_label_set_text(ui_temperature, "0"); // Default

    // After both labels are created (after previous two blocks)
    if (ui_Screen2_update_manual) {
        char dryBuf[16], tempBuf[16];
        sprintf(dryBuf, "%d", potenTimeValue);
        sprintf(tempBuf, "%d°C", potenTempValue);
        lv_label_set_text(ui_dryTime, dryBuf);
        lv_label_set_text(ui_temperature, tempBuf);
        printf("Manual transfer: temperature=%d, dryTime=%d\n", potenTempValue, potenTimeValue);
        ui_Screen2_update_manual = false;
    }

        // 2. Check for AUTO mode update (from ui_Screen3 - either preset selection or start op)
        else if (selected_dryTime > 0) {
            char dryBuf[16];
            sprintf(dryBuf, "%d", selected_dryTime);
            lv_label_set_text(ui_dryTime, dryBuf);

            char tempBuf[16];
            sprintf(tempBuf, "%d°C", selected_temperature);
            lv_label_set_text(ui_temperature, tempBuf);
        }

    ui_autoOp1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_autoOp1, 77);
    lv_obj_set_height(ui_autoOp1, 34);
    lv_obj_set_x(ui_autoOp1, -163);
    lv_obj_set_y(ui_autoOp1, -98);
    lv_obj_set_align(ui_autoOp1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_autoOp1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_autoOp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_autoOp1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autoLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_autoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_autoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_autoLabel, -165);
    lv_obj_set_y(ui_autoLabel, -92);
    lv_obj_set_align(ui_autoLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_autoLabel, "Auto");
    lv_obj_set_style_text_color(ui_autoLabel, lv_color_hex(0xFFFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_autoLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_manOp = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_manOp, 77);
    lv_obj_set_height(ui_manOp, 30);
    lv_obj_set_x(ui_manOp, -165);
    lv_obj_set_y(ui_manOp, -61);
    lv_obj_set_align(ui_manOp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_manOp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_manOp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_manOp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_manLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_manLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_manLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_manLabel, -165);
    lv_obj_set_y(ui_manLabel, -64);
    lv_obj_set_align(ui_manLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_manLabel, "Manual");
    lv_obj_set_style_text_color(ui_manLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_manLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_doorStatus = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_doorStatus, 79);
    lv_obj_set_height(ui_doorStatus, 19);
    lv_obj_set_x(ui_doorStatus, -131);
    lv_obj_set_y(ui_doorStatus, 64);
    lv_obj_set_align(ui_doorStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_doorStatus, "");

    ui_ovenStatus = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_ovenStatus, 79);
    lv_obj_set_height(ui_ovenStatus, 19);
    lv_obj_set_x(ui_ovenStatus, -130);
    lv_obj_set_y(ui_ovenStatus, 89);
    lv_obj_set_align(ui_ovenStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ovenStatus, "");

    ui_greenCircle = lv_img_create(ui_Screen2);
    lv_obj_add_flag(ui_greenCircle, LV_OBJ_FLAG_HIDDEN);
    lv_img_set_src(ui_greenCircle, &ui_img_1994032800);
    lv_obj_set_width(ui_greenCircle, LV_SIZE_CONTENT);   /// 70
    lv_obj_set_height(ui_greenCircle, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_greenCircle, -1);
    lv_obj_set_y(ui_greenCircle, 73);
    lv_obj_set_align(ui_greenCircle, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_greenCircle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_greenCircle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_redCircle = lv_img_create(ui_Screen2);
    lv_obj_add_flag(ui_redCircle, LV_OBJ_FLAG_HIDDEN);
    lv_img_set_src(ui_redCircle, &ui_img_1881266704);
    lv_obj_set_width(ui_redCircle, LV_SIZE_CONTENT);   /// 70
    lv_obj_set_height(ui_redCircle, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_redCircle, 0);
    lv_obj_set_y(ui_redCircle, 73);
    lv_obj_set_align(ui_redCircle, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_redCircle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_redCircle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_redCircle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_Screen2);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard1, 419);
    lv_obj_set_height(ui_Keyboard1, 173);
    lv_obj_set_x(ui_Keyboard1, -18);
    lv_obj_set_y(ui_Keyboard1, -44);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_HomeButton, ui_event_HomeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SimTemp, ui_event_SimTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_autoOp1, ui_event_autoOp1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_manOp, ui_event_manOp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_redCircle, ui_event_redCircle, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_SimTemp);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Image12 = NULL;
    ui_HomeButton = NULL;
    ui_Label3 = NULL;
    ui_Notif = NULL;
    ui_NotifLabel = NULL;
    ui_SimTemp = NULL;
    ui_dryTime = NULL;
    ui_temperature = NULL;
    ui_autoOp1 = NULL;
    ui_autoLabel = NULL;
    ui_manOp = NULL;
    ui_manLabel = NULL;
    ui_doorStatus = NULL;
    ui_ovenStatus = NULL;
    ui_greenCircle = NULL;
    ui_redCircle = NULL;
    ui_Keyboard1 = NULL;
}
