// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: IndustrialOven

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image12;
extern void ui_event_HomeButton(lv_event_t * e);
extern lv_obj_t * ui_HomeButton;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Notif;
extern lv_obj_t * ui_NotifLabel;
extern void ui_event_SimTemp(lv_event_t * e);
extern lv_obj_t * ui_SimTemp;
extern lv_obj_t * ui_dryTime;
extern lv_obj_t * ui_temperature;
extern void ui_event_autoOp1(lv_event_t * e);
extern lv_obj_t * ui_autoOp1;
extern lv_obj_t * ui_autoLabel;
extern void ui_event_manOp(lv_event_t * e);
extern lv_obj_t * ui_manOp;
extern lv_obj_t * ui_manLabel;
extern lv_obj_t * ui_doorStatus;
extern lv_obj_t * ui_ovenStatus;
extern lv_obj_t * ui_greenCircle;
extern void ui_event_redCircle(lv_event_t * e);
extern lv_obj_t * ui_redCircle;
extern lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

