// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: IndustrialOven

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Image4;
extern void ui_event_mainDashboardMan(lv_event_t * e);
extern lv_obj_t * ui_mainDashboardMan;
extern lv_obj_t * ui_startOpMan;
extern lv_obj_t * ui_doorStatusMan;
extern lv_obj_t * ui_ovenStatusMan;
extern lv_obj_t * ui_potenTemp;
extern lv_obj_t * ui_potentTime;
extern lv_obj_t * ui_tempDis;
extern lv_obj_t * ui_timeDis;
extern lv_obj_t * ui_tempDisLabel;
extern lv_obj_t * ui_timeDisLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

